<?php
$animals = [
    ["name" => "Woodpecker", "image" => "images/Agackakan.jpg"],
    ["name" => "Octopus", "image" => "images/Ahtapot.jpg"],
    ["name" => "Vulture", "image" => "images/Akbaba.jpg"],
    ["name" => "Scorpion", "image" => "images/Akrep.jpg"],
    ["name" => "Bee", "image" => "images/Arı.jpg"],
    ["name" => "Armadillo", "image" => "images/Armadillo.jpg"],
    ["name" => "Lion", "image" => "images/Aslan.jpg"],
    ["name" => "Horse", "image" => "images/At.jpg"],
    ["name" => "Bear", "image" => "images/Ayı.jpg"],
    ["name" => "Fish", "image" => "images/Balık.jpg"],
    ["name" => "Whale", "image" => "images/balina.jpg"],
    ["name" => "Owl", "image" => "images/baykuş.jpg"],
    ["name" => "Chameleon", "image" => "images/Bukalemun.jpg"],
    ["name" => "Grasshopper", "image" => "images/Çekirge.jpg"],
    ["name" => "Cheetah", "image" => "images/çita.jpg"],
    ["name" => "Seahorse", "image" => "images/denizatı.jpg"],
    ["name" => "Starfish", "image" => "images/Denizyıldızı.jpg"],
    ["name" => "Camel", "image" => "images/Deve.jpg"],
    ["name" => "Mouse", "image" => "images/fare.jpg"],
    ["name" => "Elephant", "image" => "images/fil.jpg"],
    ["name" => "Seal", "image" => "images/fok.jpg"],
    ["name" => "Deer", "image" => "images/geyik.jpg"],
    ["name" => "Pigeon", "image" => "images/Güvercin.jpg"],
    ["name" => "Rooster", "image" => "images/horoz.jpg"],
    ["name" => "Cow", "image" => "images/inek.jpg"],
    ["name" => "Jaguar", "image" => "images/Jaguar.jpg"],
    ["name" => "Kangaroo", "image" => "images/kanguru.jpg"],
    ["name" => "Tiger", "image" => "images/kaplan.jpg"],
    ["name" => "Tortoise", "image" => "images/Kaplumbaga.jpg"],
    ["name" => "Crow", "image" => "images/karga.jpg"],
    ["name" => "Shrimp", "image" => "images/Karides.jpg"],
    ["name" => "Ant", "image" => "images/karınca.jpg"],
    ["name" => "Eagle", "image" => "images/kartal.jpg"],
    ["name" => "Goat", "image" => "images/keçi.jpg"],
    ["name" => "Cat", "image" => "images/kedi.jpg"],
    ["name" => "Lizard", "image" => "images/kertenkele.jpg"],
    ["name" => "Hedgehog", "image" => "images/kirpi.jpg"],
    ["name" => "Dog", "image" => "images/Köpek.jpg"],
    ["name" => "Shark", "image" => "images/köpekbalığı.jpg"],
    ["name" => "Beaver", "image" => "images/Kunduz.jpg"],
    ["name" => "Frog", "image" => "images/kurbağa.jpg"],
    ["name" => "Wolf", "image" => "images/kurt.jpg"],
    ["name" => "Bird", "image" => "images/Kuş.jpg"],
    ["name" => "Lamb", "image" => "images/kuzu.jpg"],
    ["name" => "Stork", "image" => "images/Leylek.jpg"],
    ["name" => "Seagull", "image" => "images/Martı.jpg"],
    ["name" => "Monkey", "image" => "images/maymun.jpg"],
    ["name" => "Duck", "image" => "images/Ördek.jpg"],
    ["name" => "Panda", "image" => "images/panda.jpg"],
    ["name" => "Panther", "image" => "images/Panter.jpg"],
    ["name" => "Parrot", "image" => "images/Papağan.jpg"],
    ["name" => "Penguin", "image" => "images/penguen.jpg"],
    ["name" => "Snail", "image" => "images/Salyangoz.jpg"],
    ["name" => "Squirrel", "image" => "images/sincap.jpg"],
    ["name" => "Slug", "image" => "images/Sümüklüböcek.jpg"],
    ["name" => "Rabbit", "image" => "images/Tavşan.jpg"],
    ["name" => "Hen", "image" => "images/tavuk.jpg"],
    ["name" => "Fox", "image" => "images/tilki.jpg"],
    ["name" => "Crocodile", "image" => "images/timsah.jpg"],
    ["name" => "Ray", "image" => "images/vatoz.jpg"],
    ["name" => "Bat", "image" => "images/yarasa.jpg"],
    ["name" => "Crab", "image" => "images/yengeç.jpg"],
    ["name" => "Snake", "image" => "images/Yılan.jpg"],
    ["name" => "Dolphin", "image" => "images/yunus.jpg"],
    ["name" => "Dragonfly", "image" => "images/Yusufçuk.jpg"],
    ["name" => "Zebra", "image" => "images/Zebra.jpg"],
    ["name" => "Giraffe", "image" => "images/zürafa.jpg"],
    ["name" => "Pelican", "image" => "images/pelikan.jpg"],
    ["name" => "Raccoon", "image" => "images/rakun.jpg"],
    ["name" => "Mosquito", "image" => "images/Sinek.jpg"],
    ["name" => "Worm", "image" => "images/Solucan.jpg"],
    ["name" => "Hippo", "image" => "images/Su Aygiri.jpg"],
    ["name" => "Chimpanzee", "image" => "images/Sempanze.jpg"],
    ["name" => "Peacock", "image" => "images/Tavus Kusu.jpg"],
    ["name" => "Sloth", "image" => "images/tembel hayvan.jpg"],
    ["name" => "Ladybug", "image" => "images/Ugur Bocegi.jpg"]
];
?>
