<?php
$animals = [
    ["name" => "Ahtapot", "image" => "images/Ahtapot.jpg"],
    ["name" => "Arı", "image" => "images/Arı.jpg"],
    ["name" => "Aslan", "image" => "images/Aslan.jpg"],
    ["name" => "At", "image" => "images/At.jpg"],
    ["name" => "Ayı", "image" => "images/Ayı.jpg"],
    ["name" => "Balık", "image" => "images/Balık.jpg"],
    ["name" => "Balina", "image" => "images/balina.jpg"],
    ["name" => "Baykuş", "image" => "images/baykuş.jpg"],
    ["name" => "Bukalemun", "image" => "images/Bukalemun.jpg"],
    ["name" => "Çekirge", "image" => "images/Çekirge.jpg"],
    ["name" => "Çita", "image" => "images/çita.jpg"],
    ["name" => "Denizatı", "image" => "images/denizatı.jpg"],
    ["name" => "Denizyıldızı", "image" => "images/Denizyıldızı.jpg"],
    ["name" => "Deve", "image" => "images/Deve.jpg"],
    ["name" => "Fare", "image" => "images/fare.jpg"],
    ["name" => "Fil", "image" => "images/fil.jpg"],
    ["name" => "Fok", "image" => "images/fok.jpg"],
    ["name" => "Geyik", "image" => "images/geyik.jpg"],
    ["name" => "Güvercin", "image" => "images/Güvercin.jpg"],
    ["name" => "Horoz", "image" => "images/horoz.jpg"],
    ["name" => "İnek", "image" => "images/inek.jpg"],
    ["name" => "Jaguar", "image" => "images/Jaguar.jpg"],
    ["name" => "Kanguru", "image" => "images/kanguru.jpg"],
    ["name" => "Kaplan", "image" => "images/kaplan.jpg"],
    ["name" => "Kaplumbağa", "image" => "images/Kaplumbaga.jpg"],
    ["name" => "Karga", "image" => "images/karga.jpg"],
    ["name" => "Karides", "image" => "images/Karides.jpg"],
    ["name" => "Karınca", "image" => "images/karınca.jpg"],
    ["name" => "Kartal", "image" => "images/kartal.jpg"],
    ["name" => "Keçi", "image" => "images/keçi.jpg"],
    ["name" => "Kedi", "image" => "images/kedi.jpg"],
    ["name" => "Kertenkele", "image" => "images/kertenkele.jpg"],
    ["name" => "Kirpi", "image" => "images/kirpi.jpg"],
    ["name" => "Köpek", "image" => "images/Köpek.jpg"],
    ["name" => "Köpekbalığı", "image" => "images/köpekbalığı.jpg"],
    ["name" => "Kunduz", "image" => "images/Kunduz.jpg"],
    ["name" => "Kurbağa", "image" => "images/kurbağa.jpg"],
    ["name" => "Kurt", "image" => "images/kurt.jpg"],
    ["name" => "Kuş", "image" => "images/Kuş.jpg"],
    ["name" => "Kuzu", "image" => "images/kuzu.jpg"],
    ["name" => "Leylek", "image" => "images/Leylek.jpg"],
    ["name" => "Martı", "image" => "images/Martı.jpg"],
    ["name" => "Maymun", "image" => "images/maymun.jpg"],
    ["name" => "Ördek", "image" => "images/Ördek.jpg"],
    ["name" => "Panda", "image" => "images/panda.jpg"],
    ["name" => "Panter", "image" => "images/Panter.jpg"],
    ["name" => "Papağan", "image" => "images/Papağan.jpg"],
    ["name" => "Penguen", "image" => "images/penguen.jpg"],
    ["name" => "Salyangoz", "image" => "images/Salyangoz.jpg"],
    ["name" => "Sincap", "image" => "images/sincap.jpg"],
    ["name" => "Sümüklüböcek", "image" => "images/Sümüklüböcek.jpg"],
    ["name" => "Tavşan", "image" => "images/Tavşan.jpg"],
    ["name" => "Tavuk", "image" => "images/tavuk.jpg"],
    ["name" => "Tilki", "image" => "images/tilki.jpg"],
    ["name" => "Timsah", "image" => "images/timsah.jpg"],
    ["name" => "Vatoz", "image" => "images/vatoz.jpg"],
    ["name" => "Yarasa", "image" => "images/yarasa.jpg"],
    ["name" => "Yengeç", "image" => "images/yengeç.jpg"],
    ["name" => "Yılan", "image" => "images/Yılan.jpg"],
    ["name" => "Yunus", "image" => "images/yunus.jpg"],
    ["name" => "Yusufçuk", "image" => "images/Yusufçuk.jpg"],
    ["name" => "Zebra", "image" => "images/Zebra.jpg"],
    ["name" => "Zürafa", "image" => "images/zürafa.jpg"],
    ["name" => "Ağaçkakan", "image" => "images/Agackakan.jpg"],
    ["name" => "Akbaba", "image" => "images/Akbaba.jpg"],
    ["name" => "Akrep", "image" => "images/Akrep.jpg"],
    ["name" => "Armadillo", "image" => "images/Armadillo.jpg"],
    ["name" => "Deniz Kaplumbağası", "image" => "images/Deniz Kaplumbagasi.jpg"],
    ["name" => "Denizanası", "image" => "images/denizanasi.jpg"],
    ["name" => "Denizkestanesi", "image" => "images/Denizkestanesi.jpg"],
    ["name" => "Deve Kuşu", "image" => "images/Deve Kusu.jpg"],
    ["name" => "Eşek", "image" => "images/Esek.jpg"],
    ["name" => "Flamingo", "image" => "images/flamingo.jpg"],
    ["name" => "Gergedan", "image" => "images/Gergedan.jpg"],
    ["name" => "Goril", "image" => "images/goril.jpg"],
    ["name" => "İpek Böceği", "image" => "images/ipek bocegi.jpg"],
    ["name" => "Istakoz", "image" => "images/Istakoz.jpg"],
    ["name" => "Karıncayiyen", "image" => "images/Karincayiyen.jpg"],
    ["name" => "Kaz", "image" => "images/kaz.jpg"],
    ["name" => "Kelaynak", "image" => "images/kelaynak.jpg"],
    ["name" => "Kelebek", "image" => "images/kelebek.jpg"],
    ["name" => "Kılıç Balığı", "image" => "images/Kilic baligi.jpg"],
    ["name" => "Kırkayak", "image" => "images/kirkayak.jpg"],
    ["name" => "Kırlangıç", "image" => "images/kirlangic.jpg"],
    ["name" => "Koala", "image" => "images/Koala.jpg"],
    ["name" => "Kokarca", "image" => "images/kokarca.jpg"],
    ["name" => "Köstebek", "image" => "images/Kostebek.jpg"],
    ["name" => "Lama", "image" => "images/lama.jpg"],
    ["name" => "Lemur", "image" => "images/Lemur.jpg"],
    ["name" => "Midilli", "image" => "images/midilli.jpg"],
    ["name" => "Örümcek", "image" => "images/Orumcek.jpg"],
    ["name" => "Pelikan", "image" => "images/pelikan.jpg"],
    ["name" => "Rakun", "image" => "images/rakun.jpg"],
    ["name" => "Sinek", "image" => "images/Sinek.jpg"],
    ["name" => "Solucan", "image" => "images/Solucan.jpg"],
    ["name" => "Su Aygırı", "image" => "images/Su Aygiri.jpg"],
    ["name" => "Şempanze", "image" => "images/Sempanze.jpg"],
    ["name" => "Tavus Kuşu", "image" => "images/Tavus Kusu.jpg"],
    ["name" => "Tembel Hayvan", "image" => "images/tembel hayvan.jpg"],
    ["name" => "Uğur Böceği", "image" => "images/Ugur Bocegi.jpg"]
];
?>
